### ISSUE TITLE
category for simulation platforms?

### ISSUE THREAD

**Issue by ltalirz** [tilde-lab/awesome-materials-informatics#3]
In my opinion, the two categories "software frameworks" and "materials databases" are well-chosen, but I wonder whether we need a third category. 

I'm thinking of sites like nanohub, but also others like [ZEOMICS](http://helios.princeton.edu/zeomics)  / [MOFomics](http://helios.princeton.edu/mofomics), where the main benefit is not so much the database, but rather the fact that a user can upload his or her own structure (or set up a calculation in another way) and get a result back.

Unfortunately, I haven't found a very precise name for this category... my ideas so far:
* Cloud services
* Simulation platforms
* ...

**Comment by blokhin** [comment]
We are on a shaky ground here. It turns out, basically any script with an online interface (even [very simple](http://uspex-team.org/online_utilities/cif2poscar) or somehow [more complicated](http://stokes.byu.edu/iso/findsym.php)) should be called _cloud service_ or _simulation platform_. And if we try to track and include all such efforts, the list bloats and loses its value. Finally, I believe, it's not really `materials informatics`, since the `data-intensive` criterion is not met. What do you think?

**Comment by ltalirz** [comment]
Point taken. And nobody is helped if the list explodes.

What I am looking for then are some guidelines that help me decide whether something  like  [ZEOMICS](http://helios.princeton.edu/zeomics)  / [MOFomics](http://helios.princeton.edu/mofomics) should be on the list.
They have some database component as well, but I wouldn't call it machine-readable.

As in #2 I think it may be easiest to do this definition by example (what is and what isn't machine readable) rather than trying to find a general textual definition.
